CREATE TABLE IF NOT EXISTS `events_push` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TXID` char(64) NOT NULL,
  `ISPUSHED` int NOT NULL,
  `ETIME` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `TXID` (`TXID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;